#!/usr/bin/expect
# micro li
#

set timeout 30

set ip [lindex $argv 0]

for {set i 0} {$i < 3} {incr i} {
	spawn ssh "root@$ip"

	expect {
		"yes/no" {
			send "yes\n"

			expect {
				"# " {
					send "exit\n"
					break
				}
			}
		}
		"# " {
			send "exit\n"
			break
		}
		-indices -re "Offending key in (.*known_hosts)" {
			set knowHost $expect_out(1,string)
			close
			exec sed -i /$ip/d $knowHost 
			
			continue
		}
	}
	break
}

interact
