export CIOM_HOME="/opt/ciom"
export CIOM_SCRIPT_HOME="$CIOM_HOME/ciomscript"
export CIOM_VCA_HOME="$CIOM_HOME/ciomvca"
export CIOM_REPOS_HOME="$CIOM_HOME/ciomrepos"
export CIOM_APPCERT_HOME="$CIOM_HOME/ciomappcert"
export CIOM_CLI_WORKSPACE="$CIOM_HOME/ciom.cli.workspace"
export CIOM_REPO_INNER_URL="http://172.17.128.240:9999/ciomrepo"
#export CIOM_REPO_PUBLIC_URL="http://10.10.69.210:8888"
export CIOM_REPO_PUBLIC_URL="https://devops:cb64a8313ef49931446d7b86b5071ac30c8a6ee350f418344545407c5b4784a7@ciomrepo-devops.yxt.com"

export CIOM_REPO_LOCAL="/sdb/ciomrepo"
export CIOM_REPO_PUBLIC_HOST="10.10.94.215"
export CIOM_SLAVE_WIN_WORKSPACE="$CIOM_HOME/ciom.slave.win.workspace"
export CIOM_SLAVE_WIN7_WORKSPACE="$CIOM_HOME/ciom.slave.win7.workspace"
export CIOM_SLAVE_OSX_WORKSPACE="$CIOM_HOME/ciom.slave.osx.workspace"
export CIOM_SLAVE_OSX1_WORKSPACE="$CIOM_HOME/ciom.slave.osx1.workspace"
export CIOM_SLAVE_OSX2_WORKSPACE="$CIOM_HOME/ciom.slave.osx2.workspace"

export CIOM_ANDROID_BUILDER="172.17.128.251"
export CIOM_LOG_FILE="/var/log/ciom.log"
