#!/bin/bash
# by: lilongen@gmail.com
#

file=$1
passphase=$2
readonly=${3:-0}

getMd5sum() {
	echo -n $(openssl md5 $1 | awk '{print $2}')
}

getTimestamp() {
	echo -n $(date +%04Y%02m%02d.%02k%02M%02S)
}

snapshotFile() {
	timestamp=$(getTimestamp)
	cp $file $file.$timestamp
}

clean() {
	rm -rf $tmpFile
}

if [ $# -lt 1 ] || [ "$1" == "help" ] || [ "$1" == "-h" ]; then
	echo "usage:"
	echo "$0 %file %passphase"
	echo "$0 %file, and input %passphase lazzly"
	echo 
	exit 1
fi

if [ ! -f $file ]; then
	echo "file not exist!"
	exit 2
fi

if [ "$passphase" == "" ]; then
	read -s passphase
fi

# 
#--------------------------------------------------------------------------
#

tmpFile="__$file.tmp"
aesPrefix="openssl enc -aes-256-cbc -salt -a -pass pass:$passphase"

$aesPrefix -d -in $file -out $tmpFile
if [ $? -ne 0 ]; then
	echo "incorrect password!"
	clean
	exit 3
fi

if [ $readonly -eq 1 ]; then
	cat $tmpFile
	clean	
	exit 0
fi

md5sum0=$(getMd5sum $tmpFile)
vim $tmpFile
md5sum1=$(getMd5sum $tmpFile)

if [ "$md5sum0" == "$md5sum1" ]; then
	echo "no changes!"
	clean
	exit 0
fi

snapshotFile
$aesPrefix -e -in $tmpFile -out $file
clean

cat $file
