#!/bin/bash
# ciom prebuild extra action
#

perl -0 -i -pE \
's|(?<g1><artifactId>waf</artifactId>\s+<version>)(?<g2>[^<>]+)(?<g3></version>)|$+{g1}$+{g2}-ucloud-nodbproxy$+{g3}|sg' \
$WORKSPACE/api/pom.xml

perl -0 -i -pE \
's|(?<g1><stringProp name="Argument.name">ServerIP</stringProp>\s+<stringProp name="Argument.value">)[^<>]+(?<g2></stringProp>)|$+{g1}123.59.58.39$+{g2}|sg' \
$WORKSPACE/api/src/test/jmeter/api.jmx

perl -0 -i -pE \
's|(?<g1><stringProp name="Argument.name">Port</stringProp>\s+<stringProp name="Argument.value">)[^<>]+(?<g2></stringProp>)|$+{g1}8000$+{g2}|sg' \
$WORKSPACE/api/src/test/jmeter/api.jmx
