#!/bin/bash
# ciom prebuild extra action
#

perl -0 -i -pE \
's|(?<g1><artifactId>waf</artifactId>\s+<version>)(?<g2>[^<>]+)(?<g3></version>)|$+{g1}$+{g2}-dev$+{g3}|sg' \
$WORKSPACE/adminapi/pom.xml

perl -0 -i -pE \
's|(?<g1><stringProp name="Argument.name">ServerIP</stringProp>\s+<stringProp name="Argument.value">)[^<>]+(?<g2></stringProp>)|$+{g1}172.17.128.234$+{g2}|sg' \
$WORKSPACE/adminapi/src/test/jmeter/adminapi.jmx

perl -0 -i -pE \
's|(?<g1><stringProp name="Argument.name">Port</stringProp>\s+<stringProp name="Argument.value">)[^<>]+(?<g2></stringProp>)|$+{g1}8080$+{g2}|sg' \
$WORKSPACE/adminapi/src/test/jmeter/adminapi.jmx