DROP TABLE IF EXISTS qida_actionlog;
CREATE TABLE qida_actionlog (
	orgid String,
	orgname String,
	logtitle String,
	serverip String,
	clientip String,
	pageuri String,
	actionurl String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	positionid String,
	useragent String,
	referurl String,
	method String,
	target String,
	subtarget String,
	attribute String,
	description String,
	source String,
	latitude String,
	longitude String,
	logcontent String,
	referstr1 String,
	referstr2 String,
	referstr3 String,
	referstr4 String,
	referstr5 String,
	referstr6 String,
	logtime timestamp
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

DROP TABLE IF EXISTS qida_accesslog;
CREATE TABLE qida_accesslog (
	orgid String,
	orgname String,
	logtitle String,
	pagename String,
	ip String,
	pageuri String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	ouname String,
	positionid String,
	positionname String,
	useragent String,
	referurl String,
	method String,
	source String,
	logtime timestamp
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

DROP TABLE IF EXISTS lecai_actionlog;
CREATE TABLE lecai_actionlog (
	orgid String,
	orgname String,
	logtitle String,
	serverip String,
	clientip String,
	pageuri String,
	actionurl String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	positionid String,
	useragent String,
	referurl String,
	method String,
	target String,
	subtarget String,
	attribute String,
	description String,
	source String,
	latitude String,
	longitude String,
	logcontent String,
	referstr1 String,
	referstr2 String,
	referstr3 String,
	referstr4 String,
	referstr5 String,
	referstr6 String,
	logtime timestamp
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

DROP TABLE IF EXISTS lecai_accesslog;
CREATE TABLE lecai_accesslog (
	orgid String,
	orgname String,
	logtitle String,
	pagename String,
	ip String,
	pageuri String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	ouname String,
	positionid String,
	positionname String,
	useragent String,
	referurl String,
	method String,
	source String,
	logtime timestamp
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

DROP TABLE IF EXISTS mall_actionlog;
CREATE TABLE mall_actionlog (
	orgid String,
	orgname String,
	logtitle String,
	serverip String,
	clientip String,
	pageuri String,
	actionurl String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	positionid String,
	useragent String,
	referurl String,
	method String,
	target String,
	subtarget String,
	attribute String,
	description String,
	source String,
	latitude String,
	longitude String,
	logcontent String,
	referstr1 String,
	referstr2 String,
	referstr3 String,
	referstr4 String,
	referstr5 String,
	referstr6 String,
	logtime timestamp
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

DROP TABLE IF EXISTS mall_accesslog;
CREATE TABLE mall_accesslog (
	orgid String,
	orgname String,
	logtitle String,
	pagename String,
	ip String,
	pageuri String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	ouname String,
	positionid String,
	positionname String,
	useragent String,
	referurl String,
	method String,
	source String,
	logtime timestamp
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

DROP TABLE IF EXISTS wangxiao_actionlog;
CREATE TABLE wangxiao_actionlog (
	orgid String,
	orgname String,
	logtitle String,
	serverip String,
	clientip String,
	pageuri String,
	actionurl String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	positionid String,
	useragent String,
	referurl String,
	method String,
	target String,
	subtarget String,
	attribute String,
	description String,
	source String,
	latitude String,
	longitude String,
	logcontent String,
	referstr1 String,
	referstr2 String,
	referstr3 String,
	referstr4 String,
	referstr5 String,
	referstr6 String,
	logtime timestamp
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

DROP TABLE IF EXISTS wangxiao_accesslog;
CREATE TABLE wangxiao_accesslog (
	orgid String,
	orgname String,
	logtitle String,
	pagename String,
	ip String,
	pageuri String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	ouname String,
	positionid String,
	positionname String,
	useragent String,
	referurl String,
	method String,
	source String,
	logtime timestamp
) ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t';

