drop table if exist qida_actionlog;
create table qida_actionlog (
	orgid String,
	orgname String,
	logtitle String,
	serverip String,
	clientip String,
	pageuri String,
	actionurl String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	positionid String,
	useragent String,
	referurl String,
	method String,
	target String,
	subtarget String,
	attribute String,
	description String,
	source String,
	latitude String,
	longitude String,
	logcontent String,
	referstr1 String,
	referstr2 String,
	referstr3 String,
	referstr4 String,
	referstr5 String,
	referstr6 String,
	logtime timestamp
) row format delimited fields terminated by '\t';

drop table if exist qida_accesslog;
create table qida_accesslog (
	orgid String,
	orgname String,
	logtitle String,
	pagename String,
	ip String,
	pageuri String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	ouname String,
	positionid String,
	positionname String,
	useragent String,
	referurl String,
	method String,
	source String,
	logtime timestamp
) row format delimited fields terminated by '\t';

drop table if exist lecai_actionlog;
create table lecai_actionlog (
	orgid String,
	orgname String,
	logtitle String,
	serverip String,
	clientip String,
	pageuri String,
	actionurl String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	positionid String,
	useragent String,
	referurl String,
	method String,
	target String,
	subtarget String,
	attribute String,
	description String,
	source String,
	latitude String,
	longitude String,
	logcontent String,
	referstr1 String,
	referstr2 String,
	referstr3 String,
	referstr4 String,
	referstr5 String,
	referstr6 String,
	logtime timestamp
) row format delimited fields terminated by '\t';

drop table if exist lecai_accesslog;
create table lecai_accesslog (
	orgid String,
	orgname String,
	logtitle String,
	pagename String,
	ip String,
	pageuri String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	ouname String,
	positionid String,
	positionname String,
	useragent String,
	referurl String,
	method String,
	source String,
	logtime timestamp
) row format delimited fields terminated by '\t';

drop table if exist mall_actionlog;
create table mall_actionlog (
	orgid String,
	orgname String,
	logtitle String,
	serverip String,
	clientip String,
	pageuri String,
	actionurl String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	positionid String,
	useragent String,
	referurl String,
	method String,
	target String,
	subtarget String,
	attribute String,
	description String,
	source String,
	latitude String,
	longitude String,
	logcontent String,
	referstr1 String,
	referstr2 String,
	referstr3 String,
	referstr4 String,
	referstr5 String,
	referstr6 String,
	logtime timestamp
) row format delimited fields terminated by '\t';

drop table if exist mall_accesslog;
create table mall_accesslog (
	orgid String,
	orgname String,
	logtitle String,
	pagename String,
	ip String,
	pageuri String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	ouname String,
	positionid String,
	positionname String,
	useragent String,
	referurl String,
	method String,
	source String,
	logtime timestamp
) row format delimited fields terminated by '\t';

drop table if exist wangxiao_actionlog;
create table wangxiao_actionlog (
	orgid String,
	orgname String,
	logtitle String,
	serverip String,
	clientip String,
	pageuri String,
	actionurl String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	positionid String,
	useragent String,
	referurl String,
	method String,
	target String,
	subtarget String,
	attribute String,
	description String,
	source String,
	latitude String,
	longitude String,
	logcontent String,
	referstr1 String,
	referstr2 String,
	referstr3 String,
	referstr4 String,
	referstr5 String,
	referstr6 String,
	logtime timestamp
) row format delimited fields terminated by '\t';

drop table if exist wangxiao_accesslog;
create table wangxiao_accesslog (
	orgid String,
	orgname String,
	logtitle String,
	pagename String,
	ip String,
	pageuri String,
	querystring String,
	userid String,
	username String,
	usercnname String,
	sex String,
	ouid String,
	ouname String,
	positionid String,
	positionname String,
	useragent String,
	referurl String,
	method String,
	source String,
	logtime timestamp
) row format delimited fields terminated by '\t';

